#!/bin/bash
set -Eeuo pipefail

#
# Runs every generated case in tests/nss-regression/cases/ against a real NSS build and compares
# the result to each case's expect.txt. Shared by scripts/nss-regression-test.sh (local, Docker)
# and .github/workflows/nss-regression.yml (CI, workflow_dispatch) so the pass/fail logic can't
# drift between the two.
#
# Required environment:
#   NSS_DIST   Path to a built NSS Release tree (contains bin/{certutil,modutil,vfychain}, lib/).
#   MODULE     Path to the built libosclientcerts.so (release, --features nss-regression).
#   CASES_DIR  Path to tests/nss-regression/cases/ (generated by generate_chains.py).
#

: "${NSS_DIST:?NSS_DIST must point to a built NSS Release tree}"
: "${MODULE:?MODULE must point to libosclientcerts.so}"
: "${CASES_DIR:?CASES_DIR must point to tests/nss-regression/cases/}"

export LD_LIBRARY_PATH="${NSS_DIST}/lib"

FAILED=0
for CASE_DIR in "${CASES_DIR}"/*/; do
    CASE="$(basename "${CASE_DIR}")"
    EXPECT="$(cat "${CASE_DIR}/expect.txt")"

    DB="/tmp/nssdb-${CASE}"
    rm -rf "${DB}"
    mkdir -p "${DB}"
    "${NSS_DIST}/bin/certutil" -N -d "sql:${DB}" --empty-password >/dev/null

    export OSCLIENTCERTS_NSS_REGRESSION_DIR="${CASE_DIR%/}"
    "${NSS_DIST}/bin/modutil" -dbdir "sql:${DB}" -add "osclientcerts-test" -libfile "${MODULE}" -force >/dev/null 2>&1

    set +e
    OUT="$("${NSS_DIST}/bin/vfychain" -d "sql:${DB}" -a -u 5 "${CASE_DIR}leaf.pem" 2>&1)"
    RC=$?
    set -e

    if echo "${OUT}" | grep -q "Chain is good"; then
        ACTUAL="trusted"
    else
        ACTUAL="untrusted"
    fi

    if [[ "${ACTUAL}" == "${EXPECT}" ]]; then
        echo "PASS  ${CASE}  (expected=${EXPECT}, got=${ACTUAL}, exit=${RC})"
    else
        echo "FAIL  ${CASE}  (expected=${EXPECT}, got=${ACTUAL}, exit=${RC})"
        echo "------ vfychain output ------"
        echo "${OUT}"
        echo "------------------------------"
        FAILED=1
    fi
    unset OSCLIENTCERTS_NSS_REGRESSION_DIR
done

echo
if [[ "${FAILED}" -eq 0 ]]; then
    echo "============================================================"
    echo " ALL CASES PASSED"
    echo "============================================================"
else
    echo "============================================================"
    echo " SOME CASES FAILED"
    echo "============================================================"
fi
exit "${FAILED}"
